fix macos silent setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -266,15 +266,19 @@ case "${unameOut}" in
                 MISSING_LIST=$(printf " %s" "${MISSING[@]:1}")
                 MISSING_LIST=${MISSING_LIST:1}
                 if [ ${#MISSING[@]} -gt 0 ]; then 
-                    echo "You are missing the following packages: ${MISSING_LIST}"
-                    echo "Would you like us to install these packages using homebrew for you?"
-                    select yn in "Yes" "No"; do
-                        case $yn in
-                            Yes ) brew install ${MISSING_LIST}; break;;
-                            No ) echo "Please install these packages manually, then run this script again.";
-                            exit 1;;
-                        esac
-                    done
+                    if [ $SILENT -eq 1 ]; then
+                        brew install ${MISSING_LIST};
+                    else
+                        echo "You are missing the following packages: ${MISSING_LIST}"
+                        echo "Would you like us to install these packages using homebrew for you?"
+                        select yn in "Yes" "No"; do
+                            case $yn in
+                                Yes ) brew install ${MISSING_LIST}; break;;
+                                No ) echo "Please install these packages manually, then run this script again.";
+                                exit 1;;
+                            esac
+                        done
+                    fi
                 fi
                 if type xcode-select >&- && xpath=$( xcode-select --print-path ) && test -d "${xpath}" && test -x "${xpath}" ; then
                     echo -e "xcode is ${GREEN}installed${NC}."
